name: test
on: [push]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: node
      uses: actions/setup-node@v6
      with:
        node-version: "24"
    - uses: pnpm/action-setup@v6
    - run: node test/test.js
    - run: node test/mcl-test.js

