name: Check package-lock.json

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  compare-package-lock:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'

      - name: Copy package-lock.json file
        run: cp package-lock.json package-lock-copy.json

      - name: Remove package-lock.json file
        run: rm -f package-lock.json

      - name: Run npm install
        run: npm install

      - name: Compare old package-lock with generated package-lock
        run: cmp package-lock.json package-lock-copy.json
